using ZedExEss.Zx8x.Tape;

namespace ZedExEss.Zx8x.Audio;

/// <summary>
/// Converts timestamped ZX80/ZX81 MIC transitions into mono PCM for optional
/// host monitoring. The original machines contain no loudspeaker, so the machine
/// graph enables this monitor only while dense ROM cassette output is detected.
/// </summary>
/// <remarks>
/// Each PCM value is the exact time-weighted average of the digital MIC level
/// over that sample period. No slew limiter or synthetic low-pass filter changes
/// the source edge timing.
/// </remarks>
public sealed class Zx8xAudioRenderer : IZx8xCassetteOutputSink
{
    public const short DefaultMicAmplitude = 6_000;

    private readonly int _cpuHz;
    private readonly int _sampleRate;
    private readonly short _micAmplitude;
    private short[] _pending = new short[64];
    private int _pendingOffset;
    private int _pendingCount;
    private ulong _cursorTstate;
    private long _samplePhase;
    private long _sampleSum;
    private bool _captureStarted;
    private bool _micHigh = true;
    private bool _monitorEnabled;

    public Zx8xAudioRenderer(int cpuHz, int sampleRate, short micAmplitude = DefaultMicAmplitude)
    {
        ArgumentOutOfRangeException.ThrowIfNegativeOrZero(cpuHz);
        ArgumentOutOfRangeException.ThrowIfNegativeOrZero(sampleRate);
        ArgumentOutOfRangeException.ThrowIfNegativeOrZero(micAmplitude);

        _cpuHz = cpuHz;
        _sampleRate = sampleRate;
        _micAmplitude = micAmplitude;
    }

    public bool MonitorEnabled => _monitorEnabled;
    public bool MicHigh => _micHigh;

    /// <summary>
    /// Enables or disables audible MIC monitoring at an exact machine time.
    /// Disabling monitoring produces silence; it does not stop cassette output.
    /// The machine normally drives this from cassette-output activity detection;
    /// diagnostics and future UI controls may also set it explicitly.
    /// </summary>
    public void SetMonitorEnabled(bool enabled, ulong tstate)
    {
        AdvanceTo(tstate);
        _monitorEnabled = enabled;
    }

    /// <summary>Begins PCM production without changing the current MIC state.</summary>
    public void BeginCapture(ulong tstate)
    {
        if (_captureStarted)
        {
            AdvanceTo(tstate);
            return;
        }

        _captureStarted = true;
        _cursorTstate = tstate;
    }

    public void SetMicLevel(ulong tstate, bool high)
    {
        AdvanceTo(tstate);
        _micHigh = high;
    }

    /// <summary>Produces all complete PCM samples up to <paramref name="tstate"/>.</summary>
    public void AdvanceTo(ulong tstate)
    {
        if (!_captureStarted)
        {
            _cursorTstate = tstate;
            return;
        }

        if (tstate < _cursorTstate)
        {
            // A machine reset establishes a new absolute CPU timeline.
            Reset(tstate);
            return;
        }

        ulong elapsed = tstate - _cursorTstate;
        _cursorTstate = tstate;
        if (elapsed == 0)
        {
            return;
        }

        ulong units = elapsed * (ulong)_sampleRate;
        int level = CurrentLevel;
        while (units != 0)
        {
            long required = _cpuHz - _samplePhase;
            long consumed = units < (ulong)required ? (long)units : required;
            _sampleSum += (long)level * consumed;
            _samplePhase += consumed;
            units -= (ulong)consumed;

            if (_samplePhase == _cpuHz)
            {
                Enqueue((short)(_sampleSum / _cpuHz));
                _samplePhase = 0;
                _sampleSum = 0;
            }
        }
    }

    public int DrainSamples(short[] buffer, int offset, int count)
    {
        ArgumentNullException.ThrowIfNull(buffer);
        if (offset < 0 || count < 0 || offset + count > buffer.Length)
        {
            throw new ArgumentOutOfRangeException(nameof(count));
        }

        int copied = Math.Min(count, _pendingCount);
        if (copied == 0)
        {
            return 0;
        }

        Array.Copy(_pending, _pendingOffset, buffer, offset, copied);
        _pendingOffset += copied;
        _pendingCount -= copied;
        if (_pendingCount == 0)
        {
            _pendingOffset = 0;
        }

        return copied;
    }

    public void Reset(ulong tstate = 0)
    {
        _cursorTstate = tstate;
        _samplePhase = 0;
        _sampleSum = 0;
        _pendingOffset = 0;
        _pendingCount = 0;
        _captureStarted = false;
        _micHigh = true;
    }

    /// <summary>
    /// Discards PCM generated by a previous execution owner and anchors a future
    /// realtime capture at the machine's current time. Turbo execution does not
    /// consume audio, so retaining that backlog would make a newly-created audio
    /// driver drain old samples instead of advancing the CPU.
    /// </summary>
    public void DiscardPendingSamples(ulong tstate)
    {
        _cursorTstate = tstate;
        _samplePhase = 0;
        _sampleSum = 0;
        _pendingOffset = 0;
        _pendingCount = 0;
        _captureStarted = false;
    }

    private int CurrentLevel => !_monitorEnabled
        ? 0
        : (_micHigh ? _micAmplitude : -_micAmplitude);

    private void Enqueue(short sample)
    {
        EnsurePendingCapacity(1);
        _pending[_pendingOffset + _pendingCount] = sample;
        _pendingCount++;
    }

    private void EnsurePendingCapacity(int additional)
    {
        int tail = _pendingOffset + _pendingCount;
        if (_pending.Length - tail >= additional)
        {
            return;
        }

        if (_pending.Length - _pendingCount >= additional)
        {
            Array.Copy(_pending, _pendingOffset, _pending, 0, _pendingCount);
            _pendingOffset = 0;
            return;
        }

        int size = _pending.Length;
        while (size - _pendingCount < additional)
        {
            size *= 2;
        }

        var replacement = new short[size];
        Array.Copy(_pending, _pendingOffset, replacement, 0, _pendingCount);
        _pending = replacement;
        _pendingOffset = 0;
    }
}
